language: c
sudo: required
group: edge
dist: trusty
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - sudo sh -c "curl -L https://github.com/docker/compose/releases/download/1.4.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
  - sudo chmod +x /usr/local/bin/docker-compose
script:
  - docker -v
  - docker-compose -v
  - docker-compose build --no-cache
  - docker-compose run compile
  - docker-compose run test
matrix:
  include:
    - env: RUBY_VERSION=2.2.3 OPENSSL_VERSION=1.0.0s
    - env: RUBY_VERSION=2.2.3 OPENSSL_VERSION=1.0.1p
    - env: RUBY_VERSION=2.2.3 OPENSSL_VERSION=1.0.2d
  fast_finish: true
