language: c
sudo: required
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - sudo sh -c "curl -L https://github.com/docker/compose/releases/download/1.3.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
  - sudo chmod +x /usr/local/bin/docker-compose
script:
  - docker-compose run test
matrix:
  allow_failures:
    - env: RUBY_VERSION=2.2.2 OPENSSL_VERSION=0.9.8zg
  include:
    - env: RUBY_VERSION=2.2.2 OPENSSL_VERSION=0.9.8zg
    - env: RUBY_VERSION=2.2.2 OPENSSL_VERSION=1.0.0s
    - env: RUBY_VERSION=2.2.2 OPENSSL_VERSION=1.0.1p
    - env: RUBY_VERSION=2.2.2 OPENSSL_VERSION=1.0.2d
  fast_finish: true
