language: c
sudo: required
group: edge
dist: trusty
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - sudo sh -c "curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
  - sudo chmod +x /usr/local/bin/docker-compose
script:
  - docker -v
  - docker-compose -v
  - docker-compose build --no-cache
  - docker-compose run test
matrix:
  include:
    - env: RUBY_VERSION=2.3.1 OPENSSL_VERSION=1.0.0t
    - env: RUBY_VERSION=2.3.1 OPENSSL_VERSION=1.0.1t
    - env: RUBY_VERSION=2.3.1 OPENSSL_VERSION=1.0.2h
    - env: RUBY_VERSION=2.3.1 OPENSSL_VERSION=1.1.0-pre6
    - env: RUBY_VERSION=2.3.1 LIBRESSL_VERSION=2.1.10
    - env: RUBY_VERSION=2.3.1 LIBRESSL_VERSION=2.2.9
    - env: RUBY_VERSION=2.3.1 LIBRESSL_VERSION=2.3.7
    - env: RUBY_VERSION=2.3.1 LIBRESSL_VERSION=2.4.2
  fast_finish: true
  allow_failures:
    - env: RUBY_VERSION=2.3.1 OPENSSL_VERSION=1.1.0-pre6
