compile: &defaults
  build: .
  environment:
    RUBY_VERSION:
    OPENSSL_VERSION:
    MDEBUG:
  command: rake compile
test:
  <<: *defaults
  command: rake compile test
debug:
  <<: *defaults
  command: /bin/bash
